

POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NjgxNzA1OTMsInVzZXJJZCI6MH0.DY6XJLtDXUw60SbAU6wbn4WDC1g30MppSEtlifG1QL4

{
    "Name"        :"Test event",    
	"Description" :"A test event",    
	"Location"    :"a test location" ,   
	"DateTime"    :"2025-01-01T15:30:00.000Z"

}