PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "Name"        :"updated test event",    
	"Description" :"updated test event",    
	"Location"    :"updated test location" ,   
	"DateTime"    :"2025-01-01T15:30:00.000Z"
}